Algoritmo "Conta10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gui
// Descrição   :elabore um algoritmo que conte de 1 até 10
// Data atual  : 17/03/2023
Var
// Seção de Declarações das variáveis
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador <- 1
enquanto (contador<=10) faca
escreval(contador)
contador <- contador +1
fimenquanto

Fimalgoritmo