Algoritmo "ContaPara"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gui
// Descrição   : elabore um algoritmo que conte de 1 ate 10 utilizando a estrutura para
// Data atual  : 17/03/2023
Var
// Seção de Declarações das variáveis
conta:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para conta <- 1 ate 10 passo 1 faca
escreval(conta)
fimpara

Fimalgoritmo